name: mfm_parser
description: mfm (Markup Language For Misskey) parser for dart. it provides feature that text convert
              misskey node and properties.
version: 1.0.5
homepage: https://github.com/shiosyakeyakini-info/dart_mfm_parser

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
dependencies:
  collection: ^1.18.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
